FROM php:8.4-fpm-alpine AS app_php

ENV APP_ENV=prod

RUN apk update

RUN apk add --update --virtual procps autoconf g++ make libpq-dev icu-dev libzip-dev git openssh-client openssl nano \
    && apk add acl postgresql \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && docker-php-ext-install pgsql pdo_pgsql \
    && pecl channel-update pecl.php.net \
    && pecl install apcu \
    && docker-php-ext-enable apcu opcache \
    && docker-php-ext-install intl \
    && runDeps="$( \
    		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
    			| tr ',' '\n' \
    			| sort -u \
    			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    	)" \
    && apk add --no-cache --virtual .app-phpexts-rundeps $runDeps \
    && pecl clear-cache \
    && rm -rf /tmp/pear \
    && rm -rf /var/cache/apk/*

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY docker/php/php-prod.ini $PHP_INI_DIR/conf.d/php.ini

RUN mkdir -p /var/www/app
WORKDIR /var/www/app

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY composer.* symfony.* ./
# Install dependencies
RUN set -eux; \
	composer install --prefer-dist --no-autoloader --no-dev --no-scripts --no-progress; \
	composer clear-cache

COPY .env ./
COPY assets assets/
COPY bin bin/
COPY importmap.php ./
COPY config config/
COPY src src/
COPY public public/
COPY migrations migrations/
COPY translations translations/

RUN mkdir -p var/cache var/log \
    && setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/var \
    && setfacl -R -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/var \
    && setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/vendor \
    && setfacl -R -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/vendor \
    && setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/public \
    && setfacl -R -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/public \
    && setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/assets \
    && setfacl -R -m u:www-data:rwX -m u:$(whoami):rwX /var/www/app/assets

RUN set -eux \
    && composer dump-autoload --classmap-authoritative --no-dev \
    && APP_SECRET='' composer run-script post-install-cmd

RUN php bin/console asset-map:compile

COPY docker/php/docker-entrypoint-prod.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

USER www-data

ENTRYPOINT ["docker-entrypoint"]

CMD ["php-fpm"]

FROM nginx:1.24-alpine AS app_nginx

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/

WORKDIR /var/www/app/public

COPY --from=app_php /var/www/app/public ./